spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
    com.youcode: INFO
  file:
    name: logs/application.log
